# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1217, 677)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.read_file_button_1 = QtWidgets.QPushButton(self.tab)
        self.read_file_button_1.setGeometry(QtCore.QRect(20, 70, 161, 61))
        self.read_file_button_1.setObjectName("read_file_button_1")
        self.data_table_widget = QtWidgets.QTableWidget(self.tab)
        self.data_table_widget.setGeometry(QtCore.QRect(20, 170, 521, 441))
        self.data_table_widget.setObjectName("data_table_widget")
        self.data_table_widget.setColumnCount(0)
        self.data_table_widget.setRowCount(0)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.plot_widget_1 = QtWidgets.QWidget(self.tab_2)
        self.plot_widget_1.setGeometry(QtCore.QRect(30, 30, 611, 461))
        self.plot_widget_1.setObjectName("plot_widget_1")
        self.data_table_widget_2 = QtWidgets.QTableWidget(self.tab_2)
        self.data_table_widget_2.setGeometry(QtCore.QRect(680, 70, 491, 341))
        self.data_table_widget_2.setObjectName("data_table_widget_2")
        self.data_table_widget_2.setColumnCount(0)
        self.data_table_widget_2.setRowCount(0)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Робота з даними."))
        self.read_file_button_1.setText(_translate("MainWindow", "Відкрити файл"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Меню"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Статистики"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
